baseURL = 'https://samaucoinoceanography.org/'
languageCode = 'en-ca'
title = 'Sam Aucoin'
theme = 'poison'
pagination.pagerSize = 10
pluralizelisttitles = false   # removes the automatically appended "s" on sidebar entries


[params]
 	front_page_content = []
	brand = "Sam Aucoin"                      # name of your site - appears in the sidebar
    	brand_image = "/images/sam_portrait.jpg"    # path to the image shown in the sidebar
    	description = "Physical oceanographer and outdoor lover." # Used as default meta description if not specified in front matter
    	dark_mode = false                      # optional - defaults to false

    	# MENU PLACEHOLDER
    	# Menu dict keys:
        	# Name:         The name to display on the menu.
        	# URL:          The directory relative to the content directory.
        	# HasChildren:  If the directory's files should be listed.  Default is true.
        	# Limit:        If the files should be listed, how many should be shown.


menu = [
        # SINGLE PAGE
        # Note that you must put your markdown file 
        # inside of a directory with the same name.

	{Name = "Projects", URL = "/projects/", HasChildren = true, Limit = 10},
	{Name = "Publications", URL = "/publications/"},
	{Name = "Presentations", URL = "/presentations/"},
	{Name = "Activities", URL = "/activities/", HasChildren = true, Limit = 10},
    ]


# Links to your socials.  Comment or delete any you don't need/use. 
    email_url = "mailto://sam.aucoin@dal.ca"
    github_url = "https://github.com/s-aucoin"
    linkedin_url = "https://linkedin.com/in/sam-aucoin-463a241a1"
    orcid = "https://orcid.org/0009-0009-6772-3418"
    google_scholar_url = "https://scholar.google.ca/citations?hl=en&user=q93anJoAAAAJ"
    cv_url = "/files/SA_CV_2024.pdf"
    youtube_url = "https://youtube.com/@SA_Ocean"


# Hex colors for your sidebar.
# colour palette: [#181a1b, #001a33, #003366, #004080, #0059b3, #0066cc, #cce5ff, #e5f2ff, #fafcff]
    moon_sun_background_color = "#0059b3"   # default is #515151
    moon_sun_color = "#cce5ff"                 # default is #FFF
    sidebar_a_color = "#cce5ff"                # default is #FFF
    sidebar_bg_color = "#003366"            # default is #202020
    sidebar_h1_color = "#cce5ff"               # default is #FFF
    sidebar_img_border_color = "#0059b3"    # default is #515151
    sidebar_p_color = "#0066cc"             # default is #909090
    sidebar_socials_color = "#cce5ff"          # default is #FFF

    # Hex colors for your content in light mode.
    code_color = "#000"                     # default is #000
    code_background_color = "#fafcff"       # default is #E5E5E5
    code_block_color = "#cce5ff"               # default is #FFF
    code_block_background_color = "#272822" # default is #272822
    content_bg_color = "#e5f2ff"            # default is #FAF9F6
    date_color = "#0059b3"                  # default is #515151
    link_color = "#0059b3"                  # default is #268BD2
    list_color = "#5A5A5A"                  # default is #5A5A5A
    post_title_color = "#303030"            # default is #303030
    table_border_color = "#E5E5E5"          # default is #E5E5E5
    table_stripe_color = "#F9F9F9"          # default is #F9F9F9
    text_color = "#181a1b"                     # default is #222

    # Hex colors for your content in dark mode
    code_color_dark = "#e5f2ff"                        # default is #FFF
    code_background_color_dark = "#0059b3"          # default is #515151
    code_block_color_dark = "#cce5ff"                  # default is #FFF
    code_block_background_color_dark = "#272822"    # default is #272822
    content_bg_color_dark = "#001a33"               # default is #121212
    date_color_dark = "#e5f2ff"                     # default is #9A9A9A
    link_color_dark = "#0059b3"                     # default is #268BD2
    list_color_dark = "#9D9D9D"                     # default is #9D9D9D
    post_title_color_dark = "#DBE2E9"               # default is #DBE2E9
    table_border_color_dark = "#515151"             # default is #515151
    table_stripe_color_dark = "#202020"             # default is #202020
    text_color_dark = "#e5f2ff"                        # default is #EEE


    # NOTE: The following three params are optional and are used to create meta tags + enhance SEO.
    # og_image = ""                       # path to social icon - front matter: image takes precedent, then og_image, then brand_url
                                          # this is also used in the schema output as well. Image is resized to max 1200x630
                                          # For this to work though og_image and brand_url must be a path inside the assets directory
                                          # e.g. /assets/images/site/og-image.png becomes images/site/og-image.png
    # publisher_icon = ""                 # path to publisher icon - defaults to favicon, used in schema


[taxonomies]
    series = 'series'
    tags = 'tags'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[caches]
  [caches.images]
    dir = ':cacheDir/images'
